server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  cache:
    type: redis
    redis:
      key-prefix: imgs_
      time-to-live: 15m
      use-key-prefix: true
      cache-null-values: true
  redis:
    port: 6379
    host: localhost  # localhost
#    password:
  mail:
    host: smtp.qq.com
    username: awsl.simple@qq.com
    password: tciqnmxijcladhea
    port: 587
  thymeleaf:
    mode: HTML
    suffix: .html
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  codec:
    max-in-memory-size: 20MB
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

imgs:
  upload:
    dir: D:/imgs/  # absolute path for saving image
    suffix: .png.jpg.jpeg.webp.gif  # image format supported upload
    tags:
      maxNum: 3
  view:
    notFound: D:/imgs/not_found.jpg  # absolute path





